# Basic cleaning

In [48]:
import pandas as pd

## Cleaning Population DS

In [2]:
# Importing the file
original_pop_db = pd.read_excel('Population.xlsx')

original_pop_db.head(10)

,ANO,GEO_COD,GEO_COD_DSG,NIVEL,NIVEL_DSG,N_INDIVIDUOS_RESIDENT,N_INDIVIDUOS_RESIDENT_H,N_INDIVIDUOS_RESIDENT_M
0,2011,'PT,PT,1,Total Nacional,10562178,5046600,5515578
1,2011,'1,Continente,2,NUT1,10047621,4798798,5248823
2,2011,'17,Lisboa,3,NUT2,2821876,1334605,1487271
3,2011,'171,Grande Lisboa,4,NUT3,2042477,961132,1081345
4,2011,'1106,Lisboa,5,Municipio,547733,250874,296859
5,2011,'110601,Ajuda,6,Freguesia,15584,7120,8464
6,2011,'110602,Alcântara,6,Freguesia,13943,6254,7689
7,2011,'110603,Alto do Pina,6,Freguesia,10333,4687,5646
8,2011,'110604,Alvalade,6,Freguesia,8869,3764,5105
9,2011,'110605,Ameixoeira,6,",",11863,5568,6295

In [3]:
# Selecting just the cols that we want to display
pop_db = original_pop_db[['GEO_COD_DSG', 'NIVEL_DSG', 'N_INDIVIDUOS_RESIDENT']]


# Filtering to just get the rows which match 'Freguesia' - helped to get rid of all blank values
pop_db = pop_db[(pop_db['NIVEL_DSG'] == 'Freguesia')]


# Selecting new cols that we want
pop_db = pop_db[['GEO_COD_DSG', 'N_INDIVIDUOS_RESIDENT']]

pop_db.head(10)

     GEO_COD_DSG  N_INDIVIDUOS_RESIDENT
5          Ajuda                  15584
6      Alcântara                  13943
7   Alto do Pina                  10333
8       Alvalade                   8869
10         Anjos                   9361
11         Beato                  12429
12       Benfica                  36821
13  Campo Grande                  10514
14     Campolide                  15460
15       Carnide                  23316

In [4]:
# Renaming the columns
pop_db.columns = ['FREGUESIAS', 'TOTAL RESIDENTS']


# Making 'FREGUESIAS' column have .upper values
pop_db['FREGUESIAS'] = pop_db['FREGUESIAS'].str.upper()

pop_db.head(10)

      FREGUESIAS  TOTAL RESIDENTS
5          AJUDA            15584
6      ALCÂNTARA            13943
7   ALTO DO PINA            10333
8       ALVALADE             8869
10         ANJOS             9361
11         BEATO            12429
12       BENFICA            36821
13  CAMPO GRANDE            10514
14     CAMPOLIDE            15460
15       CARNIDE            23316

In [5]:
pop_db.shape

(52, 2)

## Cleaning Freguesias DS

In [6]:
# Importing the file
original_freguesias_db = pd.read_csv('Freguesias2012.csv')


original_freguesias_db['FREGUESIAS53'] = original_freguesias_db['FREGUESIAS53'].str.upper()
original_freguesias_db.head(10)

,OBJECTID,COD_SIG,NOME,IDTIPO,PERIMETRO,AREA_M2,FREGUESIAS53,GlobalID,Shape__Area,Shape__Length
0,1,122,Santo António,4015,6313.94,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,9de1ceba-f851-4181-a39b-a4f8bc15f3c5,2.458057e+06,8097.074172
1,2,118,Parque das Nações,4015,12237.24,5435124.30,SANTA MARIA DOS OLIVAIS,aee6efb3-c624-4d82-b5f8-a98c4444b8c6,8.953807e+06,15724.284710
2,3,115,Marvila,4015,12216.54,7122521.90,MARVILA,d6c144c0-6ffc-46d7-b6bf-f10fa7977b89,1.172476e+07,15674.400259
3,4,101,Ajuda,4015,9153.10,2876647.11,AJUDA,cdcaeb5c-7228-4a89-9091-9fb9be097e6e,4.730508e+06,11740.588160
4,5,104,Areeiro,4015,6358.83,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,d1e276ef-009e-4290-a8b8-73643141a71e,2.829203e+06,8153.225327
5,6,121,Santa Maria Maior,4015,9306.07,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,60af311b-84fb-4a39-856a-291d65993f97,4.952034e+06,11936.070712
6,7,103,Alvalade,4015,10751.30,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,e9ec7868-7b40-478a-87b3-c6ad6e373e5a,8.794657e+06,13786.968033
7,8,108,Belém,4015,16050.78,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,3a6d0af1-130a-4c90-80f6-b6017dac1ca1,1.713895e+07,20577.231795
8,9,113,Estrela,4015,9927.92,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,ba35868d-aa59-40db-8737-469f48274ce9,7.569528e+06,12734.386771
9,10,105,Arroios,4015,8240.38,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,ec8fa8b1-49e5-49bb-a311-1f51aafa5e77,3.500783e+06,10572.552949

In [7]:
# Selecting the cols that we want to keep
freguesias_db = original_freguesias_db[['NOME', 'AREA_M2', 'FREGUESIAS53']]


# Renaming the cols
freguesias_db.columns = ['CURRENT FREGUESIAS', 'AREA', 'OLD FREGUESIAS']


# Making the Freguesias names be .upper()

freguesias_db['CURRENT FREGUESIAS'] = freguesias_db['CURRENT FREGUESIAS'].str.upper()
main_db = freguesias_db

#freguesias_db.head(10)
main_db

/Users/mattymrc/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE
1,PARQUE DAS NAÇÕES,5435124.30,SANTA MARIA DOS OLIVAIS
2,MARVILA,7122521.90,MARVILA
3,AJUDA,2876647.11,AJUDA
4,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS
5,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...
6,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO
7,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER
8,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO
9,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS
10,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA
11,AVENIDAS NOVAS,2994523.99,NOSSA SENHORA DE FÁTIMA + SÃO SEBASTIÃO DA PED...
12,CARNIDE,3688827.32,CARNIDE
13,SÃO DOMINGOS DE BENFICA,4294403.21,SÃO DOMINGOS DE BENFICA
14,BEATO,2483775.04,BEATO
15,CAMPOLIDE,2774372.95,CAMPOLIDE
16,ALCÂNTARA,5074843.76,ALCÂNTARA
17,CAMPO DE OURIQUE,1651405.17,SANTA ISABEL + SANTO CONDESTÁVEL
18,SÃO VICENTE,1985855.99,GRAÇA + SANTA ENGRÁCIA + SÃO VICENTE DE FORA
19,OLIVAIS,8088293.95,SANTA MARIA DOS OLIVAIS
20,MISERICÓRDIA,2192198.78,ENCARNAÇÃO + MERCÊS + SANTA CATARINA + SÃO PAULO
21,LUMIAR,6574930.77,LUMIAR
22,PENHA DE FRANÇA,2710760.87,PENHA DE FRANÇA + SÃO JOÃO
23,BENFICA,8024544.82,BENFICA

## Cleaning Public Lighting DS

In [8]:
# Importing the file
original_lights_db = pd.read_excel('candeeiros.xls')
original_lights_db.head(10)

,X,Y,OBJECTID_1,FREGUESIA,TIPOLOGIA,COD_SIG,MORADA,GlobalID
0,-9.141983,38.710343,2001,SANTA MARIA MAIOR,Consola,320058790.0,Rua Paiva de Andrada,52dcd30e-57f5-453c-9455-deb7784e97d9
1,-9.142045,38.709027,2002,SANTA MARIA MAIOR,Consola,320059024.0,Largo do Picadeiro,d14a744d-b274-4253-9820-5db4e22072ae
2,-9.141898,38.709226,2003,SANTA MARIA MAIOR,Consola,320058467.0,Largo do Picadeiro,b2689a5a-ce30-44b2-b70c-7de1eb9fdadf
3,-9.141974,38.709676,2004,SANTA MARIA MAIOR,Consola,320058468.0,Largo do Picadeiro,4e3d4e6a-0cfc-4029-b127-d375b80a6e90
4,-9.139831,38.722655,2005,ARROIOS,Coluna,320058551.0,Campo dos Mártires da Pátria,d3aef766-296b-4d94-bf2d-92b2c5dd1691
5,-9.139617,38.722630,2006,ARROIOS,Coluna,320058078.0,Campo dos Mártires da Pátria,90f4b46a-5bdd-44e1-9bf7-f7659304c481
6,-9.139928,38.722669,2007,ARROIOS,Coluna,320058181.0,Campo dos Mártires da Pátria,a63d3be0-dcc2-4723-ad28-7081c55472dc
7,-9.140245,38.722624,2008,ARROIOS,Coluna,320058141.0,Campo dos Mártires da Pátria,041912a9-7f2b-4af7-958e-0a7b7b85ddd6
8,-9.140179,38.722510,2009,ARROIOS,Coluna,320058552.0,Campo dos Mártires da Pátria,2dc9338e-30fe-4b1c-92ec-7c55bed91b74
9,-9.140049,38.722626,2010,ARROIOS,Coluna,320058182.0,Campo dos Mártires da Pátria,f9654514-3675-4c30-9b4d-03ea9f4a655e

In [9]:
# Selecting the cols we want
lights_db = original_lights_db[['OBJECTID_1', 'FREGUESIA', 'MORADA']]

# Renaming the cols
lights_db.columns = ['OBJECT NUMBER', 'CURRENT FREGUESIAS', 'PUBLIC LIGHTS']

lights_db.head(10)

   OBJECT NUMBER CURRENT FREGUESIAS                 PUBLIC LIGHTS
0           2001  SANTA MARIA MAIOR          Rua Paiva de Andrada
1           2002  SANTA MARIA MAIOR            Largo do Picadeiro
2           2003  SANTA MARIA MAIOR            Largo do Picadeiro
3           2004  SANTA MARIA MAIOR            Largo do Picadeiro
4           2005            ARROIOS  Campo dos Mártires da Pátria
5           2006            ARROIOS  Campo dos Mártires da Pátria
6           2007            ARROIOS  Campo dos Mártires da Pátria
7           2008            ARROIOS  Campo dos Mártires da Pátria
8           2009            ARROIOS  Campo dos Mártires da Pátria
9           2010            ARROIOS  Campo dos Mártires da Pátria

In [10]:
# Checking the shape
lights_db.shape

(62840, 3)

In [11]:
#count lights for each freguesia
lights_grouped = lights_db.groupby(['CURRENT FREGUESIAS'], as_index = False).agg({'PUBLIC LIGHTS':'count'})

main_db = pd.merge(main_db, lights_grouped, on='CURRENT FREGUESIAS', how='left')

main_db

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,PUBLIC LIGHTS
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,1573
1,PARQUE DAS NAÇÕES,5435124.30,SANTA MARIA DOS OLIVAIS,3235
2,MARVILA,7122521.90,MARVILA,4386
3,AJUDA,2876647.11,AJUDA,1873
4,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,1975
5,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,2071
6,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,3881
7,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,2965
8,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,2167
9,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,2005
10,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA,2469
11,AVENIDAS NOVAS,2994523.99,NOSSA SENHORA DE FÁTIMA + SÃO SEBASTIÃO DA PED...,3035
12,CARNIDE,3688827.32,CARNIDE,2166
13,SÃO DOMINGOS DE BENFICA,4294403.21,SÃO DOMINGOS DE BENFICA,2962
14,BEATO,2483775.04,BEATO,996
15,CAMPOLIDE,2774372.95,CAMPOLIDE,2128
16,ALCÂNTARA,5074843.76,ALCÂNTARA,1693
17,CAMPO DE OURIQUE,1651405.17,SANTA ISABEL + SANTO CONDESTÁVEL,1457
18,SÃO VICENTE,1985855.99,GRAÇA + SANTA ENGRÁCIA + SÃO VICENTE DE FORA,1127
19,OLIVAIS,8088293.95,SANTA MARIA DOS OLIVAIS,4489
20,MISERICÓRDIA,2192198.78,ENCARNAÇÃO + MERCÊS + SANTA CATARINA + SÃO PAULO,1606
21,LUMIAR,6574930.77,LUMIAR,5802
22,PENHA DE FRANÇA,2710760.87,PENHA DE FRANÇA + SÃO JOÃO,1540
23,BENFICA,8024544.82,BENFICA,4055

# NEW THINGS FROM HERE ON

## Cleaning Health Centers DS

In [12]:
original_health_db = pd.read_csv('Health centers.csv')

In [13]:
#selecting the columns with the data that we need

health_db = original_health_db[['ACTIVIDADE_NOME', 'FREGUESIA']]
health_db.columns = ['HEALTH CENTER', 'CURRENT FREGUESIAS']
health_db['CURRENT FREGUESIAS'] = health_db['CURRENT FREGUESIAS'].str.upper()


health_db.head(10)

/Users/mattymrc/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

                                    HEALTH CENTER CURRENT FREGUESIAS
0                                 Centro de Saúde              BELÉM
1                          Centro de Saúde Lumiar             LUMIAR
2                          Centro de Saúde Lumiar             LUMIAR
3                                 Centro de Saúde              BELÉM
4                                 Centro de Saúde              BELÉM
5  Centro de Saúde de Sete Rios - Ext.Sãvida /EDP     AVENIDAS NOVAS
6                     Centro de Saúde de São João    PENHA DE FRANÇA
7              Unidade de Saúde Familiar da Baixa  SANTA MARIA MAIOR
8                   Clínica Médica Ferreira Diniz              BELÉM
9                      Laboratório de Pneumologia          ALCÂNTARA

In [14]:
count_health = health_db.groupby(by='CURRENT FREGUESIAS', as_index=False).agg('count')
count_health.columns = ['CURRENT FREGUESIAS', 'HEALTH CENTER']
count_health
main_db = pd.merge(main_db, count_health, on='CURRENT FREGUESIAS', how='left')

main_db

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,PUBLIC LIGHTS,HEALTH CENTER
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,1573,4.0
1,PARQUE DAS NAÇÕES,5435124.30,SANTA MARIA DOS OLIVAIS,3235,NaN
2,MARVILA,7122521.90,MARVILA,4386,7.0
3,AJUDA,2876647.11,AJUDA,1873,2.0
4,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,1975,2.0
5,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,2071,15.0
6,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,3881,8.0
7,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,2965,5.0
8,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,2167,9.0
9,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,2005,7.0
10,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA,2469,NaN
11,AVENIDAS NOVAS,2994523.99,NOSSA SENHORA DE FÁTIMA + SÃO SEBASTIÃO DA PED...,3035,9.0
12,CARNIDE,3688827.32,CARNIDE,2166,1.0
13,SÃO DOMINGOS DE BENFICA,4294403.21,SÃO DOMINGOS DE BENFICA,2962,3.0
14,BEATO,2483775.04,BEATO,996,NaN
15,CAMPOLIDE,2774372.95,CAMPOLIDE,2128,2.0
16,ALCÂNTARA,5074843.76,ALCÂNTARA,1693,4.0
17,CAMPO DE OURIQUE,1651405.17,SANTA ISABEL + SANTO CONDESTÁVEL,1457,2.0
18,SÃO VICENTE,1985855.99,GRAÇA + SANTA ENGRÁCIA + SÃO VICENTE DE FORA,1127,2.0
19,OLIVAIS,8088293.95,SANTA MARIA DOS OLIVAIS,4489,4.0
20,MISERICÓRDIA,2192198.78,ENCARNAÇÃO + MERCÊS + SANTA CATARINA + SÃO PAULO,1606,9.0
21,LUMIAR,6574930.77,LUMIAR,5802,4.0
22,PENHA DE FRANÇA,2710760.87,PENHA DE FRANÇA + SÃO JOÃO,1540,2.0
23,BENFICA,8024544.82,BENFICA,4055,3.0

## Cleaning Police DS

In [15]:
# Importing the dataset
original_police_db = pd.read_csv('Police stations.csv')

original_police_db.head(5)

,X,Y,OBJECTID,COD_SIG,IDTIPO,COD_SIG_EDIF,NOME,MORADA,TIPO_UNIDADE,TELEFONE,EMAIL,CODPOSTAL,FONTE,MORADA_RMOG,GlobalID
0,-9.124780,38.752021,1,2105705006001021,999,2105705006001,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",Esquadra de Polícia,-,-,-,PSP,Rua Ricardo Ornelas (antigo Impasse A4 do B. F...,21788845-91be-4b5d-af40-f183b0016061
1,-9.135952,38.717907,2,3100303072001001,999,3100303072001,Comando - 1ª Divisão Policial LX,"Rua da Palma, 169",Comando,213513600,-,1100-391,PSP,"Rua da Palma 169, R/C",801d5d4e-4943-421e-accb-23f56dc0d0ad
2,-9.126077,38.739351,3,302704025001001,999,302704025001,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",Esquadra de Polícia,-,-,-,PSP,"Largo Roque Laia 3A, R/C-Loja A",cc8b174b-fb7e-45f9-af5f-bbc406846953
3,-9.151055,38.726657,4,5001301001001002,999,5001301001001,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",Vários,-,-,-,PSP,"Alameda Edgar Cardoso Estacionamento, -1",23a42e6b-cb83-47fb-b8cb-6ec6d785cda9
4,-9.136034,38.709358,5,1900102007001004,999,1900102007001,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",Esquadra de Polícia,213427379,-,1100-524,PSP,"Rua da Prata 38, R/C",6875624f-dec8-4ed4-9c4d-dd16995b3df3

In [16]:
#selecting the only columns that we need
police_db = original_police_db[['NOME', 'MORADA','CODPOSTAL']]

police_db.head(5)

,NOME,MORADA,CODPOSTAL
0,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",-
1,Comando - 1ª Divisão Policial LX,"Rua da Palma, 169",1100-391
2,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",-
3,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",-
4,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524

In [17]:
# Checking which lines have no postcode
nopostcode = police_db[police_db['CODPOSTAL'] == '-']

nopostcode

,NOME,MORADA,CODPOSTAL
0,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",-
2,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",-
3,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",-
5,Secção de Achados,Alameda das Comunidades Portuguesas Terminal 1...,-
81,Esquadra de Turismo,Largo do Museu de Artilharia,-

In [18]:
# Checking the shape
police_db.shape

(90, 3)

In [19]:
# Finding duplicated addresses and removing them. Consider these as one police division
police_db.drop_duplicates(subset = "MORADA", keep = False, inplace = True)

#police_db

/Users/mattymrc/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [20]:
#drop all rows with - on postal code
police_db.drop(police_db[police_db['CODPOSTAL'] == '-'].index, axis=0, inplace=True)

/Users/mattymrc/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pandas/core/frame.py:4117: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [21]:
#resetting the index
police_db.reset_index(drop=True, inplace=True)

#police_db

In [22]:
#creating new columns for Freguesias
police_db['Freguesia'] = police_db['CODPOSTAL']

#police_db

/Users/mattymrc/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [23]:
#dropping police estalishments that are not stations
police_db.drop(police_db[police_db['NOME'] == 'Secção de Achados'].index, axis=0, inplace=True)
police_db.drop(police_db[police_db['NOME'] == 'Instituto Superior de Ciências Policiais e Segurança Interna'].index, axis=0, inplace=True)
police_db.drop(police_db[police_db['NOME'] == 'Parque de Viaturas Rebocadas'].index, axis=0, inplace=True)
police_db.drop(police_db[police_db['NOME'] == 'Carreira de Tiro da Escola Superior de Polícia'].index, axis=0, inplace=True)

In [24]:
#resetting index
police_db.reset_index(drop=True, inplace=True)

police_db.head()

,NOME,MORADA,CODPOSTAL,Freguesia
0,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524,1100-524
1,Divisão Policial de Segurança a Transportes Pú...,Estação CP Rossio Ed. Posto do Comando,1200-147,1200-147
2,1ª Esquadra de Segurança a Transportes Públicos,Praça do Marquês de Pombal Estação de Metro (M...,1250-161,1250-161
3,Esquadra de Investigação Criminal,"Estação CP Rossio, Edifício do Chefe da Estação",1200-147,1200-147
4,Tribunal de Monsanto - Esquadra Especial,Estrada do Forte (Monsanto) Tribunal,1500-624,1500-624

In [25]:
#inserting freguesia name
police_db.at[0, 'Freguesia'] = 'São Nicolau'
police_db.at[1, 'Freguesia'] = 'Santo António'
police_db.at[2, 'Freguesia'] = 'Santa Maria Maior'
police_db.at[3, 'Freguesia'] = 'Santo António'
police_db.at[4, 'Freguesia'] = 'Benfica'
police_db.at[5, 'Freguesia'] = 'Olivais'
police_db.at[6, 'Freguesia'] = 'Santo António'
police_db.at[7, 'Freguesia'] = 'Ajuda'
police_db.at[8, 'Freguesia'] = 'Santa Maria Maior'
police_db.at[9, 'Freguesia'] = 'Arroios'
police_db.at[10, 'Freguesia'] = 'Campo Grande'
police_db.at[11, 'Freguesia'] = 'Belém'
police_db.at[12, 'Freguesia'] = 'Campolide'
police_db.at[13, 'Freguesia'] = 'Misericórdia'
police_db.at[14, 'Freguesia'] = 'Santo António'
police_db.at[15, 'Freguesia'] = 'Olivais'
police_db.at[16, 'Freguesia'] = 'Olivais'
police_db.at[17, 'Freguesia'] = 'Marvila'
police_db.at[18, 'Freguesia'] = 'Marvila'
police_db.at[19, 'Freguesia'] = 'Moscavide'
police_db.at[20, 'Freguesia'] = 'Benfica'
police_db.at[21, 'Freguesia'] = 'Benfica'
police_db.at[22, 'Freguesia'] = 'Belém'
police_db.at[23, 'Freguesia'] = 'Belém'
police_db.at[24, 'Freguesia'] = 'Estrela'
police_db.at[25, 'Freguesia'] = 'Benfica'
police_db.at[26, 'Freguesia'] = 'Benfica'

In [26]:
police_db.at[27, 'Freguesia'] = 'Campo Grande'
police_db.at[28, 'Freguesia'] = 'Lumiar'
police_db.at[29, 'Freguesia'] = 'Benfica'
police_db.at[30, 'Freguesia'] = 'Campolide'
police_db.at[31, 'Freguesia'] = 'Carnide'
police_db.at[32, 'Freguesia'] = 'Carnide'
police_db.at[33, 'Freguesia'] = 'Campolide'
police_db.at[34, 'Freguesia'] = 'Lumiar'
police_db.at[35, 'Freguesia'] = 'Carnide'
police_db.at[36, 'Freguesia'] = 'Benfica'
police_db.at[37, 'Freguesia'] = 'Carnide'
police_db.at[38, 'Freguesia'] = 'Alcântara'
police_db.at[39, 'Freguesia'] = 'Campo de Ourique'
police_db.at[40, 'Freguesia'] = 'Belém'
police_db.at[41, 'Freguesia'] = 'Alcântara'
police_db.at[42, 'Freguesia'] = 'Estrela'
police_db.at[43, 'Freguesia'] = 'Santa Maria Maior'
police_db.at[44, 'Freguesia'] = 'Areeiro'

In [27]:
police_db  = police_db

In [28]:
police_db = police_db[['NOME', 'Freguesia']]


count_police = police_db.groupby(by='Freguesia', as_index=False).agg('count')

count_police.columns = ['CURRENT FREGUESIAS', 'POLICE']
count_police['CURRENT FREGUESIAS'] = count_police['CURRENT FREGUESIAS'].str.upper()


count_police

main_db = pd.merge(main_db, count_police, on='CURRENT FREGUESIAS', how='left')

## Merge Population into Freguesia

In [29]:
freguesias_db.head()

# 1 Create a dictionary for matching old FREGUESIAs with new Fregeusias with New as keys and List of old as value
dict_change=freguesias_db[['CURRENT FREGUESIAS','OLD FREGUESIAS']].to_dict('list')

liste_old_Fregue = [s.split(' + ') for s in freguesias_db['OLD FREGUESIAS']]
liste_new_Fregue = freguesias_db['CURRENT FREGUESIAS']

dictionaryNEW_OLD = dict(zip(liste_new_Fregue,liste_old_Fregue))

#print(len(dictionaryNEW_OLD))


# 2change list of values = OLD FREGUESIAS to key and add New Frequesias as value
dictionaryOLD_NEW={} 
count=-1
for value in dictionaryNEW_OLD.values():
    count +=1
    for x in value:
        dictionaryOLD_NEW[x]=list(dictionaryNEW_OLD.keys())[count]
#print(len(dictionaryOLD_NEW))
        
# 3 import dictionary in to a dataframe
dfOLD_NEW=pd.DataFrame.from_dict(dictionaryOLD_NEW, orient='index', columns=['CURRENT FREGUESIAS']).reset_index()
dfOLD_NEW.columns=['FREGUESIAS','CURRENT FREGUESIAS']
#print(dfOLD_NEW)

# 4 add the New FREGUESIAs to the population dataframe
pop_new = pd.merge(pop_db, dfOLD_NEW, on='FREGUESIAS', how ='left')
#print(pop_new)
#print(pop_db)
# 5 group the population by the new FREGUESIAs
pop_grouped = pop_new.groupby(['CURRENT FREGUESIAS'], as_index=False).agg({'TOTAL RESIDENTS':'sum'})

# 6 merge the population with the frequesias
main_db= pd.merge(main_db, pop_grouped, on='CURRENT FREGUESIAS')
main_db

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,PUBLIC LIGHTS,HEALTH CENTER,POLICE,TOTAL RESIDENTS
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,1573,4.0,4.0,11855
1,MARVILA,7122521.90,MARVILA,4386,7.0,2.0,38102
2,AJUDA,2876647.11,AJUDA,1873,2.0,1.0,15584
3,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,1975,2.0,1.0,20131
4,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,2071,15.0,3.0,12961
5,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,3881,8.0,NaN,31110
6,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,2965,5.0,4.0,16561
7,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,2167,9.0,2.0,20116
8,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,2005,7.0,1.0,32262
9,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA,2469,NaN,NaN,9935
10,AVENIDAS NOVAS,2994523.99,NOSSA SENHORA DE FÁTIMA + SÃO SEBASTIÃO DA PED...,3035,9.0,NaN,21625
11,CARNIDE,3688827.32,CARNIDE,2166,1.0,4.0,23316
12,SÃO DOMINGOS DE BENFICA,4294403.21,SÃO DOMINGOS DE BENFICA,2962,3.0,NaN,33745
13,BEATO,2483775.04,BEATO,996,NaN,NaN,12429
14,CAMPOLIDE,2774372.95,CAMPOLIDE,2128,2.0,3.0,15460
15,ALCÂNTARA,5074843.76,ALCÂNTARA,1693,4.0,2.0,13943
16,CAMPO DE OURIQUE,1651405.17,SANTA ISABEL + SANTO CONDESTÁVEL,1457,2.0,1.0,22132
17,SÃO VICENTE,1985855.99,GRAÇA + SANTA ENGRÁCIA + SÃO VICENTE DE FORA,1127,2.0,NaN,14575
18,OLIVAIS,8088293.95,SANTA MARIA DOS OLIVAIS,4489,4.0,3.0,51036
19,MISERICÓRDIA,2192198.78,ENCARNAÇÃO + MERCÊS + SANTA CATARINA + SÃO PAULO,1606,9.0,1.0,13041
20,LUMIAR,6574930.77,LUMIAR,5802,4.0,2.0,41163
21,PENHA DE FRANÇA,2710760.87,PENHA DE FRANÇA + SÃO JOÃO,1540,2.0,NaN,27967
22,BENFICA,8024544.82,BENFICA,4055,3.0,7.0,36821

## Cleaning Average Cost of Living

In [30]:
cost_of_living_db = pd.read_excel('Avg cost of living.xlsx')

cost_of_living_db['Current Freguesias'] = cost_of_living_db['Current Freguesias'].str.upper()
cost_of_living_db.columns = ['CURRENT FREGUESIAS', 'COST OF LIVING']

cost_of_living_db.head()

  CURRENT FREGUESIAS  COST OF LIVING
0              AJUDA          271.61
1          ALCÂNTARA          308.09
2           ALVALADE          381.83
3            AREEIRO          410.26
4            ARROIOS          372.80

In [31]:
main_db = pd.merge(main_db, cost_of_living_db, on='CURRENT FREGUESIAS', how='left')

main_db.head()

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,PUBLIC LIGHTS,HEALTH CENTER,POLICE,TOTAL RESIDENTS,COST OF LIVING
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,1573,4.0,4.0,11855,386.26
1,MARVILA,7122521.90,MARVILA,4386,7.0,2.0,38102,212.79
2,AJUDA,2876647.11,AJUDA,1873,2.0,1.0,15584,271.61
3,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,1975,2.0,1.0,20131,410.26
4,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,2071,15.0,3.0,12961,273.20

## Creating Density column

In [32]:
main_db['DENSITY'] = main_db['AREA'] / main_db['TOTAL RESIDENTS']
main_db.head(10)

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,PUBLIC LIGHTS,HEALTH CENTER,POLICE,TOTAL RESIDENTS,COST OF LIVING,DENSITY
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,1573,4.0,4.0,11855,386.26,126.052179
1,MARVILA,7122521.90,MARVILA,4386,7.0,2.0,38102,212.79,186.933019
2,AJUDA,2876647.11,AJUDA,1873,2.0,1.0,15584,271.61,184.589779
3,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,1975,2.0,1.0,20131,410.26,85.390814
4,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,2071,15.0,3.0,12961,273.20,232.357960
5,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,3881,8.0,NaN,31110,381.83,171.705272
6,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,2965,5.0,4.0,16561,431.90,629.608652
7,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,2167,9.0,2.0,20116,376.04,228.877310
8,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,2005,7.0,1.0,32262,372.80,65.955982
9,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA,2469,NaN,NaN,9935,280.87,337.751644

## NEW: rearrange columns

In [33]:
main_db = main_db[['CURRENT FREGUESIAS', 'PUBLIC LIGHTS','HEALTH CENTER','POLICE','TOTAL RESIDENTS','AREA','DENSITY', 'COST OF LIVING']]

## Summary Statistics

In [34]:
main_db.describe()

,PUBLIC LIGHTS,HEALTH CENTER,POLICE,TOTAL RESIDENTS,AREA,DENSITY,COST OF LIVING
count,23.000000,21.000000,16.000000,23.000000,2.300000e+01,23.000000,23.000000
mean,2540.043478,4.952381,2.562500,23298.695652,4.113873e+06,192.542209,339.298261
std,1231.158711,3.513918,1.631717,11194.274906,2.437941e+06,119.686334,60.571762
min,996.000000,1.000000,1.000000,9935.000000,1.494349e+06,65.955982,212.790000
25%,1649.500000,2.000000,1.000000,14259.000000,2.337987e+06,131.755635,296.720000
50%,2128.000000,4.000000,2.000000,20131.000000,3.011592e+06,168.100512,330.690000
75%,3000.000000,7.000000,3.250000,31686.000000,5.208297e+06,208.885498,384.045000
max,5802.000000,15.000000,7.000000,51036.000000,1.042695e+07,629.608652,431.900000

## Relative values (NEW!!)

In [35]:
# Filling with 0's the NaNs
main_db['HEALTH CENTER'] = main_db['HEALTH CENTER'].fillna(0)
main_db['POLICE'] = main_db['POLICE'].fillna(0)


# RELATIVE VALUES
main_db['PUBLIC LIGHTS P.P. and KM2'] = main_db['PUBLIC LIGHTS'] / main_db['DENSITY']
main_db['HEALTH CENTER P.P. and KM2'] = main_db['HEALTH CENTER'] / main_db['DENSITY']
main_db['POLICE P.P. and KM2'] = main_db['POLICE'] / main_db['DENSITY']

main_db.head(10)

,CURRENT FREGUESIAS,PUBLIC LIGHTS,HEALTH CENTER,POLICE,TOTAL RESIDENTS,AREA,DENSITY,COST OF LIVING,PUBLIC LIGHTS P.P. and KM2,HEALTH CENTER P.P. and KM2,POLICE P.P. and KM2
0,SANTO ANTÓNIO,1573,4.0,4.0,11855,1494348.58,126.052179,386.26,12.478959,0.031733,0.031733
1,MARVILA,4386,7.0,2.0,38102,7122521.90,186.933019,212.79,23.462950,0.037447,0.010699
2,AJUDA,1873,2.0,1.0,15584,2876647.11,184.589779,271.61,10.146824,0.010835,0.005417
3,AREEIRO,1975,2.0,1.0,20131,1719002.47,85.390814,410.26,23.128952,0.023422,0.011711
4,SANTA MARIA MAIOR,2071,15.0,3.0,12961,3011591.52,232.357960,273.20,8.912972,0.064556,0.012911
5,ALVALADE,3881,8.0,0.0,31110,5341751.02,171.705272,381.83,22.602684,0.046591,0.000000
6,BELÉM,2965,5.0,4.0,16561,10426948.88,629.608652,431.90,4.709275,0.007941,0.006353
7,ESTRELA,2167,9.0,2.0,20116,4604095.97,228.877310,376.04,9.467955,0.039322,0.008738
8,ARROIOS,2005,7.0,1.0,32262,2127871.88,65.955982,372.80,30.399062,0.106131,0.015162
9,SANTA CLARA,2469,0.0,0.0,9935,3355562.58,337.751644,280.87,7.310105,0.000000,0.000000

## Rank of Cost of Living (NEW!!)

In [36]:
#test = pd.DataFrame.fillna(main_db, value = 0)
#test.head()
#main_db.isnull().sum()

In [37]:
mpg_labels= [x for x in range(1,11)]

main_db['POINT PUBLIC LIGHTS'] = pd.cut(main_db['PUBLIC LIGHTS P.P. and KM2'], 10, labels = mpg_labels)
main_db['POINT HEALTH CENTER'] = pd.cut(main_db['HEALTH CENTER P.P. and KM2'], 10, labels = mpg_labels)
main_db['POINT POLICE'] = pd.cut(main_db['POLICE P.P. and KM2'], 10, labels = mpg_labels)

#main_db['TOTAL POINT SI'] = main_db['POINT PUBLIC LIGHTS'] + main_db['POINT HEALTH CENTER'] + main_db['POINT POLICE'] 

#main_db['RANK COST OF LIVING'] = pd.cut(main_db['COST OF LIVING'], 10, labels = mpg_labels)

main_db.head()

,CURRENT FREGUESIAS,PUBLIC LIGHTS,HEALTH CENTER,POLICE,TOTAL RESIDENTS,AREA,DENSITY,COST OF LIVING,PUBLIC LIGHTS P.P. and KM2,HEALTH CENTER P.P. and KM2,POLICE P.P. and KM2,POINT PUBLIC LIGHTS,POINT HEALTH CENTER,POINT POLICE
0,SANTO ANTÓNIO,1573,4.0,4.0,11855,1494348.58,126.052179,386.26,12.478959,0.031733,0.031733,3,3,10
1,MARVILA,4386,7.0,2.0,38102,7122521.90,186.933019,212.79,23.462950,0.037447,0.010699,6,4,4
2,AJUDA,1873,2.0,1.0,15584,2876647.11,184.589779,271.61,10.146824,0.010835,0.005417,2,2,2
3,AREEIRO,1975,2.0,1.0,20131,1719002.47,85.390814,410.26,23.128952,0.023422,0.011711,6,3,4
4,SANTA MARIA MAIOR,2071,15.0,3.0,12961,3011591.52,232.357960,273.20,8.912972,0.064556,0.012911,2,7,5

In [38]:
main_db['TOTAL POINTS SI'] = main_db.iloc[:,-3:].sum(axis = 1)

main_db.head(10)

,CURRENT FREGUESIAS,PUBLIC LIGHTS,HEALTH CENTER,POLICE,TOTAL RESIDENTS,AREA,DENSITY,COST OF LIVING,PUBLIC LIGHTS P.P. and KM2,HEALTH CENTER P.P. and KM2,POLICE P.P. and KM2,POINT PUBLIC LIGHTS,POINT HEALTH CENTER,POINT POLICE,TOTAL POINTS SI
0,SANTO ANTÓNIO,1573,4.0,4.0,11855,1494348.58,126.052179,386.26,12.478959,0.031733,0.031733,3,3,10,16.0
1,MARVILA,4386,7.0,2.0,38102,7122521.90,186.933019,212.79,23.462950,0.037447,0.010699,6,4,4,14.0
2,AJUDA,1873,2.0,1.0,15584,2876647.11,184.589779,271.61,10.146824,0.010835,0.005417,2,2,2,6.0
3,AREEIRO,1975,2.0,1.0,20131,1719002.47,85.390814,410.26,23.128952,0.023422,0.011711,6,3,4,13.0
4,SANTA MARIA MAIOR,2071,15.0,3.0,12961,3011591.52,232.357960,273.20,8.912972,0.064556,0.012911,2,7,5,14.0
5,ALVALADE,3881,8.0,0.0,31110,5341751.02,171.705272,381.83,22.602684,0.046591,0.000000,6,5,1,12.0
6,BELÉM,2965,5.0,4.0,16561,10426948.88,629.608652,431.90,4.709275,0.007941,0.006353,1,1,2,4.0
7,ESTRELA,2167,9.0,2.0,20116,4604095.97,228.877310,376.04,9.467955,0.039322,0.008738,2,4,3,9.0
8,ARROIOS,2005,7.0,1.0,32262,2127871.88,65.955982,372.80,30.399062,0.106131,0.015162,9,10,5,24.0
9,SANTA CLARA,2469,0.0,0.0,9935,3355562.58,337.751644,280.87,7.310105,0.000000,0.000000,1,1,1,3.0

## Compare Social Infrastructure and Cost of Living !! NEW

In [39]:
compare_SI_CoL = main_db[['CURRENT FREGUESIAS','COST OF LIVING','TOTAL POINTS SI', 'POINT PUBLIC LIGHTS','POINT HEALTH CENTER','POINT POLICE',]]

compare_SI_CoL.head(10)

,CURRENT FREGUESIAS,COST OF LIVING,TOTAL POINTS SI,POINT PUBLIC LIGHTS,POINT HEALTH CENTER,POINT POLICE
0,SANTO ANTÓNIO,386.26,16.0,3,3,10
1,MARVILA,212.79,14.0,6,4,4
2,AJUDA,271.61,6.0,2,2,2
3,AREEIRO,410.26,13.0,6,3,4
4,SANTA MARIA MAIOR,273.20,14.0,2,7,5
5,ALVALADE,381.83,12.0,6,5,1
6,BELÉM,431.90,4.0,1,1,2
7,ESTRELA,376.04,9.0,2,4,3
8,ARROIOS,372.80,24.0,9,10,5
9,SANTA CLARA,280.87,3.0,1,1,1

In [43]:
compare_SI_CoL.sort_values(by = 'TOTAL POINTS SI', ascending = False)

,COST OF LIVING,TOTAL POINTS SI,POINT PUBLIC LIGHTS,POINT HEALTH CENTER,POINT POLICE
8,372.80,24.0,9.0,10.0,5.0
22,324.95,17.0,5.0,2.0,10.0
20,428.16,17.0,10.0,3.0,4.0
18,330.69,17.0,8.0,3.0,6.0
0,386.26,16.0,3.0,3.0,10.0
1,212.79,14.0,6.0,4.0,4.0
4,273.20,14.0,2.0,7.0,5.0
10,421.45,14.0,6.0,7.0,1.0
3,410.26,13.0,6.0,3.0,4.0
16,344.07,13.0,5.0,3.0,5.0
5,381.83,12.0,6.0,5.0,1.0
11,317.42,12.0,3.0,1.0,8.0
14,325.87,11.0,3.0,2.0,6.0
12,412.61,10.0,6.0,3.0,1.0
19,321.15,10.0,2.0,6.0,2.0
7,376.04,9.0,2.0,4.0,3.0
21,330.75,7.0,4.0,2.0,1.0
2,271.61,6.0,2.0,2.0,2.0
15,308.09,5.0,1.0,2.0,2.0
17,285.35,5.0,2.0,2.0,1.0
6,431.90,4.0,1.0,1.0,2.0
13,255.74,3.0,1.0,1.0,1.0
9,280.87,3.0,1.0,1.0,1.0

In [41]:
compare_SI_CoL=compare_SI_CoL[['COST OF LIVING','TOTAL POINTS SI', 'POINT PUBLIC LIGHTS','POINT HEALTH CENTER','POINT POLICE']].astype(float)
correlationMatrix =compare_SI_CoL.corr()['COST OF LIVING']
correlationMatrix

COST OF LIVING         1.000000
TOTAL POINTS SI        0.300281
POINT PUBLIC LIGHTS    0.423057
POINT HEALTH CENTER    0.187328
POINT POLICE           0.017965
Name: COST OF LIVING, dtype: float64

### Export (NEW!!)

In [51]:
#main_db.to_csv('Final Project 2.csv')
compare_SI_CoL.to_csv('Final Project Result.csv')