# Basic cleaning

In [82]:
import pandas as pd

## Cleaning Population DS

In [83]:
# Importing the file
original_pop_db = pd.read_excel('Population.xlsx')

original_pop_db.head(10)

,ANO,GEO_COD,GEO_COD_DSG,NIVEL,NIVEL_DSG,N_INDIVIDUOS_RESIDENT,N_INDIVIDUOS_RESIDENT_H,N_INDIVIDUOS_RESIDENT_M
0,2011,'PT,PT,1,Total Nacional,10562178,5046600,5515578
1,2011,'1,Continente,2,NUT1,10047621,4798798,5248823
2,2011,'17,Lisboa,3,NUT2,2821876,1334605,1487271
3,2011,'171,Grande Lisboa,4,NUT3,2042477,961132,1081345
4,2011,'1106,Lisboa,5,Municipio,547733,250874,296859
5,2011,'110601,Ajuda,6,Freguesia,15584,7120,8464
6,2011,'110602,Alcântara,6,Freguesia,13943,6254,7689
7,2011,'110603,Alto do Pina,6,Freguesia,10333,4687,5646
8,2011,'110604,Alvalade,6,Freguesia,8869,3764,5105
9,2011,'110605,Ameixoeira,6,",",11863,5568,6295

In [3]:
# Selecting just the cols that we want to display
pop_db = original_pop_db[['GEO_COD_DSG', 'NIVEL_DSG', 'N_INDIVIDUOS_RESIDENT']]


# Filtering to just get the rows which match 'Freguesia' - helped to get rid of all blank values
pop_db = pop_db[(pop_db['NIVEL_DSG'] == 'Freguesia')]


# Selecting new cols that we want
pop_db = pop_db[['GEO_COD_DSG', 'N_INDIVIDUOS_RESIDENT']]

pop_db.head(10)

     GEO_COD_DSG  N_INDIVIDUOS_RESIDENT
5          Ajuda                  15584
6      Alcântara                  13943
7   Alto do Pina                  10333
8       Alvalade                   8869
10         Anjos                   9361
11         Beato                  12429
12       Benfica                  36821
13  Campo Grande                  10514
14     Campolide                  15460
15       Carnide                  23316

In [4]:
# Renaming the columns
pop_db.columns = ['FREGUESIAS', 'TOTAL RESIDENTS']


# Making 'FREGUESIAS' column have .upper values
pop_db['FREGUESIAS'] = pop_db['FREGUESIAS'].str.upper()

pop_db.head(10)

      FREGUESIAS  TOTAL RESIDENTS
5          AJUDA            15584
6      ALCÂNTARA            13943
7   ALTO DO PINA            10333
8       ALVALADE             8869
10         ANJOS             9361
11         BEATO            12429
12       BENFICA            36821
13  CAMPO GRANDE            10514
14     CAMPOLIDE            15460
15       CARNIDE            23316

In [5]:
pop_db.shape

(52, 2)

## Cleaning Freguesias DS

In [6]:
# Importing the file
original_freguesias_db = pd.read_csv('Freguesias2012.csv')


original_freguesias_db['FREGUESIAS53'] = original_freguesias_db['FREGUESIAS53'].str.upper()
original_freguesias_db.head(10)

,OBJECTID,COD_SIG,NOME,IDTIPO,PERIMETRO,AREA_M2,FREGUESIAS53,GlobalID,Shape__Area,Shape__Length
0,1,122,Santo António,4015,6313.94,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,9de1ceba-f851-4181-a39b-a4f8bc15f3c5,2.458057e+06,8097.074172
1,2,118,Parque das Nações,4015,12237.24,5435124.30,SANTA MARIA DOS OLIVAIS,aee6efb3-c624-4d82-b5f8-a98c4444b8c6,8.953807e+06,15724.284710
2,3,115,Marvila,4015,12216.54,7122521.90,MARVILA,d6c144c0-6ffc-46d7-b6bf-f10fa7977b89,1.172476e+07,15674.400259
3,4,101,Ajuda,4015,9153.10,2876647.11,AJUDA,cdcaeb5c-7228-4a89-9091-9fb9be097e6e,4.730508e+06,11740.588160
4,5,104,Areeiro,4015,6358.83,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,d1e276ef-009e-4290-a8b8-73643141a71e,2.829203e+06,8153.225327
5,6,121,Santa Maria Maior,4015,9306.07,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,60af311b-84fb-4a39-856a-291d65993f97,4.952034e+06,11936.070712
6,7,103,Alvalade,4015,10751.30,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,e9ec7868-7b40-478a-87b3-c6ad6e373e5a,8.794657e+06,13786.968033
7,8,108,Belém,4015,16050.78,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,3a6d0af1-130a-4c90-80f6-b6017dac1ca1,1.713895e+07,20577.231795
8,9,113,Estrela,4015,9927.92,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,ba35868d-aa59-40db-8737-469f48274ce9,7.569528e+06,12734.386771
9,10,105,Arroios,4015,8240.38,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,ec8fa8b1-49e5-49bb-a311-1f51aafa5e77,3.500783e+06,10572.552949

In [7]:
# Selecting the cols that we want to keep
freguesias_db = original_freguesias_db[['NOME', 'AREA_M2', 'FREGUESIAS53']]


# Renaming the cols
freguesias_db.columns = ['CURRENT FREGUESIAS', 'AREA', 'OLD FREGUESIAS']


# Making the Freguesias names be .upper()

freguesias_db['CURRENT FREGUESIAS'] = freguesias_db['CURRENT FREGUESIAS'].str.upper()


freguesias_db.head(10)

/Users/mattymrc/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE
1,PARQUE DAS NAÇÕES,5435124.30,SANTA MARIA DOS OLIVAIS
2,MARVILA,7122521.90,MARVILA
3,AJUDA,2876647.11,AJUDA
4,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS
5,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...
6,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO
7,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER
8,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO
9,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS

## Cleaning Public Lighting DS

In [8]:
# Importing the file
original_lights_db = pd.read_csv('Candeeiros.csv')

original_lights_db.head(10)

,X,Y,OBJECTID_1,FREGUESIA,TIPOLOGIA,COD_SIG,MORADA,GlobalID
0,-9.141983,38.710343,2001,SANTA MARIA MAIOR,Consola,320058790.0,Rua Paiva de Andrada,52dcd30e-57f5-453c-9455-deb7784e97d9
1,-9.142045,38.709027,2002,SANTA MARIA MAIOR,Consola,320059024.0,Largo do Picadeiro,d14a744d-b274-4253-9820-5db4e22072ae
2,-9.141898,38.709226,2003,SANTA MARIA MAIOR,Consola,320058467.0,Largo do Picadeiro,b2689a5a-ce30-44b2-b70c-7de1eb9fdadf
3,-9.141974,38.709676,2004,SANTA MARIA MAIOR,Consola,320058468.0,Largo do Picadeiro,4e3d4e6a-0cfc-4029-b127-d375b80a6e90
4,-9.139831,38.722655,2005,ARROIOS,Coluna,320058551.0,Campo dos Mártires da Pátria,d3aef766-296b-4d94-bf2d-92b2c5dd1691
5,-9.139617,38.722630,2006,ARROIOS,Coluna,320058078.0,Campo dos Mártires da Pátria,90f4b46a-5bdd-44e1-9bf7-f7659304c481
6,-9.139928,38.722669,2007,ARROIOS,Coluna,320058181.0,Campo dos Mártires da Pátria,a63d3be0-dcc2-4723-ad28-7081c55472dc
7,-9.140245,38.722624,2008,ARROIOS,Coluna,320058141.0,Campo dos Mártires da Pátria,041912a9-7f2b-4af7-958e-0a7b7b85ddd6
8,-9.140179,38.722510,2009,ARROIOS,Coluna,320058552.0,Campo dos Mártires da Pátria,2dc9338e-30fe-4b1c-92ec-7c55bed91b74
9,-9.140049,38.722626,2010,ARROIOS,Coluna,320058182.0,Campo dos Mártires da Pátria,f9654514-3675-4c30-9b4d-03ea9f4a655e

In [9]:
# Selecting the cols we want
lights_db = original_lights_db[['OBJECTID_1', 'FREGUESIA', 'MORADA']]


# Renaming the cols
lights_db.columns = ['OBJECT NUMBER', 'FREGUESIA', 'ADDRESS']


lights_db.head(10)

   OBJECT NUMBER          FREGUESIA                       ADDRESS
0           2001  SANTA MARIA MAIOR          Rua Paiva de Andrada
1           2002  SANTA MARIA MAIOR            Largo do Picadeiro
2           2003  SANTA MARIA MAIOR            Largo do Picadeiro
3           2004  SANTA MARIA MAIOR            Largo do Picadeiro
4           2005            ARROIOS  Campo dos Mártires da Pátria
5           2006            ARROIOS  Campo dos Mártires da Pátria
6           2007            ARROIOS  Campo dos Mártires da Pátria
7           2008            ARROIOS  Campo dos Mártires da Pátria
8           2009            ARROIOS  Campo dos Mártires da Pátria
9           2010            ARROIOS  Campo dos Mártires da Pátria

In [10]:
# Checking the shape
lights_db.shape

(62840, 3)

# NEW THINGS FROM HERE ON

## Cleaning Health Centers DS

In [11]:
original_health_db = pd.read_csv('Health centers.csv')

In [12]:
#selecting the columns with the data that we need

health_db = original_health_db[['ACTIVIDADE_NOME', 'FREGUESIA']]
health_db.columns = ['Health Center', 'Freguesia']
health_db.head(10)

                                    Health Center          Freguesia
0                                 Centro de Saúde              Belém
1                          Centro de Saúde Lumiar             Lumiar
2                          Centro de Saúde Lumiar             Lumiar
3                                 Centro de Saúde              Belém
4                                 Centro de Saúde              Belém
5  Centro de Saúde de Sete Rios - Ext.Sãvida /EDP     Avenidas Novas
6                     Centro de Saúde de São João    Penha de França
7              Unidade de Saúde Familiar da Baixa  Santa Maria Maior
8                   Clínica Médica Ferreira Diniz              Belém
9                      Laboratório de Pneumologia          Alcântara

## Cleaning Police DS

In [13]:
# Importing the dataset
original_police_db = pd.read_csv('Police stations.csv')

original_police_db.head(5)

,X,Y,OBJECTID,COD_SIG,IDTIPO,COD_SIG_EDIF,NOME,MORADA,TIPO_UNIDADE,TELEFONE,EMAIL,CODPOSTAL,FONTE,MORADA_RMOG,GlobalID
0,-9.124780,38.752021,1,2105705006001021,999,2105705006001,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",Esquadra de Polícia,-,-,-,PSP,Rua Ricardo Ornelas (antigo Impasse A4 do B. F...,21788845-91be-4b5d-af40-f183b0016061
1,-9.135952,38.717907,2,3100303072001001,999,3100303072001,Comando - 1ª Divisão Policial LX,"Rua da Palma, 169",Comando,213513600,-,1100-391,PSP,"Rua da Palma 169, R/C",801d5d4e-4943-421e-accb-23f56dc0d0ad
2,-9.126077,38.739351,3,302704025001001,999,302704025001,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",Esquadra de Polícia,-,-,-,PSP,"Largo Roque Laia 3A, R/C-Loja A",cc8b174b-fb7e-45f9-af5f-bbc406846953
3,-9.151055,38.726657,4,5001301001001002,999,5001301001001,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",Vários,-,-,-,PSP,"Alameda Edgar Cardoso Estacionamento, -1",23a42e6b-cb83-47fb-b8cb-6ec6d785cda9
4,-9.136034,38.709358,5,1900102007001004,999,1900102007001,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",Esquadra de Polícia,213427379,-,1100-524,PSP,"Rua da Prata 38, R/C",6875624f-dec8-4ed4-9c4d-dd16995b3df3

In [14]:
#selecting the only columns that we need
police_db = original_police_db[['NOME', 'MORADA','CODPOSTAL']]
police_db.head(5)

,NOME,MORADA,CODPOSTAL
0,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",-
1,Comando - 1ª Divisão Policial LX,"Rua da Palma, 169",1100-391
2,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",-
3,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",-
4,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524

In [15]:
# Checking which lines have no postcode
nopostcode = police_db[police_db['CODPOSTAL'] == '-']

nopostcode

,NOME,MORADA,CODPOSTAL
0,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",-
2,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",-
3,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",-
5,Secção de Achados,Alameda das Comunidades Portuguesas Terminal 1...,-
81,Esquadra de Turismo,Largo do Museu de Artilharia,-

In [16]:
# Checking the shape
police_db.shape

(90, 3)

In [17]:
# Finding duplicated addresses and removing them. Consider these as one police division
police_db.drop_duplicates(subset = "MORADA", keep = False, inplace = True)

police_db

/Users/mattymrc/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,NOME,MORADA,CODPOSTAL
0,38ª Esquadra,"Rua Ricardo Ornelas Lote 378, R/C-A",-
2,12ª Esquadra,"Largo Roque Laia 3A, R/C Loja A",-
3,Parque de Viaturas Rebocadas,"Alameda Edgar Cardoso Estacionamento, -1",-
4,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524
5,Secção de Achados,Alameda das Comunidades Portuguesas Terminal 1...,-
16,Divisão Policial de Segurança a Transportes Pú...,Estação CP Rossio Ed. Posto do Comando,1200-147
17,1ª Esquadra de Segurança a Transportes Públicos,Praça do Marquês de Pombal Estação de Metro (M...,1250-161
18,Esquadra de Investigação Criminal,"Estação CP Rossio, Edifício do Chefe da Estação",1200-147
19,Tribunal de Monsanto - Esquadra Especial,Estrada do Forte (Monsanto) Tribunal,1500-624
21,4º Esquadra de Segurança a Transportes Públicos,"Avenida Dom João II, Estação do Oriente Lt. 01...",1990-233
26,Direção Nacional da PSP - Departamento de Arma...,"Travessa da Fábrica dos Pentes 22, 1º",1269-003
27,Instituto Superior de Ciências Policiais e Seg...,Rua Primeiro de Maio a Alcântara 3 R/C,1349-040
28,Carreira de Tiro da Escola Superior de Polícia,Rua Primeiro de Maio a Alcântara 3 R/C,1349-040
29,Corpo de Intervenção,"Calçada da Ajuda, 23",1300-006
30,Secção de Achados,"Praça Cidade de Salazar Lote 180, R/C",1800-125
31,Esquadra de Turismo,Praça dos Restauradores - Palácio Foz,1250-187
32,Posto de Polícia,"Rua José António Serrano Bloco Central, R/C",1150-199
33,Posto de Polícia,Avenida Professor Egas Moniz Hospital de San...,1649-035
34,Posto de Polícia,Estrada do Forte do Alto do Duque Hospital S F...,1449-005
35,Parque de Viaturas Rebocadas,"Azinhaga Torre do Fato, s/n",1600-298
36,Parque de Viaturas Rebocadas,"Rua Gregório Lopes, PSP",1400-195
37,Polícia Municipal,"Rua Cardeal Saraiva, R/C",1070-045
38,3ª Esquadra,"Rua da Atalaia 138-144, R/C, Rua de O Século ...",1200-033
40,22ª Esquadra LX,"Largo do Rato, 1",1250-185
41,2ª Divisão Policial LX,Rua Cidade de Nampula (antiga Rua B2 de Olivai...,1800-105
43,Esquadra de Intervenção e Fiscalização Policial,"Avenida Cidade Lourenço Marques, Praceta A",1800-093
44,14ª Esquadra LX,Rua Luiz Pacheco Lote 105,1950-244
45,16ª Esquadra LX,"Avenida João Paulo II Lote 526, R/C",1950-159
47,40ª Esquadra,"Rua Ilha dos Amores, Lote 43901-J, Parque das ...",1990-371
48,3ª Divisão Policial LX,"Rua André de Resende, R/C",1500-040
49,Esquadra de Segurança,"Palácio de Belém, s/n",1349-022
50,Esquadra de Segurança,"Praça de São Bento, s/n",1249-068
51,Esquadra de Segurança,"Rua Professor Gomes Teixeira 2, R/C",1350-265
52,Esquadra de Segurança,"Rua da Imprensa à Estrela, 4",1200-888
53,Esquadra de Segurança,"Avenida João Crisóstomo Casa da Moeda, R/C",1500-624
56,Esquadra de Intervenção e Fiscalização Policial,"Rua André de Resende, 1",1500-040
57,18ª Esquadra LX,"Rua Afonso Lopes Vieira 2A, R/C",1700-093
58,19ª Esquadra LX,"Rua Professor Luís Reis dos Santos, Lote H - 4...",1600-641
59,20ª Esquadra LX,Rua André de Resende 1,1500-040
60,21ª Esquadra LX,"Rua Marquês de Fronteira Tribunal da Policia, ...",1098-001
61,32ª Esquadra,Rua Alfredo Ferraz (antigo Impasse B1 do Bairr...,1600-003
62,36ª Esquadra,Rua Prof. Miller Guerra (antigo Impasse A do B...,1600-647
63,37ª Esquadra,"Rua Miguel Ângelo de Blasco 25, R/C",1070-181
64,41ª Esquadra,"Rua Maria José da Guia, 14 B - Bairro da Cruz ...",1750-358
65,42ª Esquadra,"Rua Manuela Porto, 14 - A",1500-422
66,43ª Esquadra LX,Rua do Azevinho (Rua B) Quarteirão Central B -...,1500-536
67,Posto de Polícia,Rua Albert Einstein (antiga R Norte - C.C.Colo...,1500-676
68,4ª Divisão Policial,"Largo do Calvário 6, 1º",1300-113
71,24ª Esquadra LX,"Rua Azedo Gneco 84, R/C",1350-039
72,26ª Esquadra LX,"Praça Afonso de Albuquerque PSP, R/C",1300-004
73,28ª Esquadra LX,"Largo do Calvário 6, R/C",1300-113
74,30ª Esquadra,"Rua Miguel Lupi 6, R/C",1200-725
78,10ª Esquadra Lx,"Rua de Arroios, 164 - A",1000-061
80,12ª Esquadra LX,"Rua Américo Durão, 3, A-B",1900-063
81,Esquadra de Turismo,Largo do Museu de Artilharia,-

In [18]:
#drop all rows with - on postal code
police_db.drop(police_db[police_db['CODPOSTAL'] == '-'].index, axis=0, inplace=True)

/Users/mattymrc/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pandas/core/frame.py:4117: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [19]:
#resetting the index
police_db.reset_index(drop=True, inplace=True)
police_db

,NOME,MORADA,CODPOSTAL
0,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524
1,Divisão Policial de Segurança a Transportes Pú...,Estação CP Rossio Ed. Posto do Comando,1200-147
2,1ª Esquadra de Segurança a Transportes Públicos,Praça do Marquês de Pombal Estação de Metro (M...,1250-161
3,Esquadra de Investigação Criminal,"Estação CP Rossio, Edifício do Chefe da Estação",1200-147
4,Tribunal de Monsanto - Esquadra Especial,Estrada do Forte (Monsanto) Tribunal,1500-624
5,4º Esquadra de Segurança a Transportes Públicos,"Avenida Dom João II, Estação do Oriente Lt. 01...",1990-233
6,Direção Nacional da PSP - Departamento de Arma...,"Travessa da Fábrica dos Pentes 22, 1º",1269-003
7,Instituto Superior de Ciências Policiais e Seg...,Rua Primeiro de Maio a Alcântara 3 R/C,1349-040
8,Carreira de Tiro da Escola Superior de Polícia,Rua Primeiro de Maio a Alcântara 3 R/C,1349-040
9,Corpo de Intervenção,"Calçada da Ajuda, 23",1300-006
10,Secção de Achados,"Praça Cidade de Salazar Lote 180, R/C",1800-125
11,Esquadra de Turismo,Praça dos Restauradores - Palácio Foz,1250-187
12,Posto de Polícia,"Rua José António Serrano Bloco Central, R/C",1150-199
13,Posto de Polícia,Avenida Professor Egas Moniz Hospital de San...,1649-035
14,Posto de Polícia,Estrada do Forte do Alto do Duque Hospital S F...,1449-005
15,Parque de Viaturas Rebocadas,"Azinhaga Torre do Fato, s/n",1600-298
16,Parque de Viaturas Rebocadas,"Rua Gregório Lopes, PSP",1400-195
17,Polícia Municipal,"Rua Cardeal Saraiva, R/C",1070-045
18,3ª Esquadra,"Rua da Atalaia 138-144, R/C, Rua de O Século ...",1200-033
19,22ª Esquadra LX,"Largo do Rato, 1",1250-185
20,2ª Divisão Policial LX,Rua Cidade de Nampula (antiga Rua B2 de Olivai...,1800-105
21,Esquadra de Intervenção e Fiscalização Policial,"Avenida Cidade Lourenço Marques, Praceta A",1800-093
22,14ª Esquadra LX,Rua Luiz Pacheco Lote 105,1950-244
23,16ª Esquadra LX,"Avenida João Paulo II Lote 526, R/C",1950-159
24,40ª Esquadra,"Rua Ilha dos Amores, Lote 43901-J, Parque das ...",1990-371
25,3ª Divisão Policial LX,"Rua André de Resende, R/C",1500-040
26,Esquadra de Segurança,"Palácio de Belém, s/n",1349-022
27,Esquadra de Segurança,"Praça de São Bento, s/n",1249-068
28,Esquadra de Segurança,"Rua Professor Gomes Teixeira 2, R/C",1350-265
29,Esquadra de Segurança,"Rua da Imprensa à Estrela, 4",1200-888
30,Esquadra de Segurança,"Avenida João Crisóstomo Casa da Moeda, R/C",1500-624
31,Esquadra de Intervenção e Fiscalização Policial,"Rua André de Resende, 1",1500-040
32,18ª Esquadra LX,"Rua Afonso Lopes Vieira 2A, R/C",1700-093
33,19ª Esquadra LX,"Rua Professor Luís Reis dos Santos, Lote H - 4...",1600-641
34,20ª Esquadra LX,Rua André de Resende 1,1500-040
35,21ª Esquadra LX,"Rua Marquês de Fronteira Tribunal da Policia, ...",1098-001
36,32ª Esquadra,Rua Alfredo Ferraz (antigo Impasse B1 do Bairr...,1600-003
37,36ª Esquadra,Rua Prof. Miller Guerra (antigo Impasse A do B...,1600-647
38,37ª Esquadra,"Rua Miguel Ângelo de Blasco 25, R/C",1070-181
39,41ª Esquadra,"Rua Maria José da Guia, 14 B - Bairro da Cruz ...",1750-358
40,42ª Esquadra,"Rua Manuela Porto, 14 - A",1500-422
41,43ª Esquadra LX,Rua do Azevinho (Rua B) Quarteirão Central B -...,1500-536
42,Posto de Polícia,Rua Albert Einstein (antiga R Norte - C.C.Colo...,1500-676
43,4ª Divisão Policial,"Largo do Calvário 6, 1º",1300-113
44,24ª Esquadra LX,"Rua Azedo Gneco 84, R/C",1350-039
45,26ª Esquadra LX,"Praça Afonso de Albuquerque PSP, R/C",1300-004
46,28ª Esquadra LX,"Largo do Calvário 6, R/C",1300-113
47,30ª Esquadra,"Rua Miguel Lupi 6, R/C",1200-725
48,10ª Esquadra Lx,"Rua de Arroios, 164 - A",1000-061
49,12ª Esquadra LX,"Rua Américo Durão, 3, A-B",1900-063

In [20]:
#creating new columns for Freguesias
police_db['Freguesia'] = police_db['CODPOSTAL']

/Users/mattymrc/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [21]:
#dropping police estalishments that are not stations
police_db.drop(police_db[police_db['NOME'] == 'Secção de Achados'].index, axis=0, inplace=True)
police_db.drop(police_db[police_db['NOME'] == 'Instituto Superior de Ciências Policiais e Segurança Interna'].index, axis=0, inplace=True)
police_db.drop(police_db[police_db['NOME'] == 'Parque de Viaturas Rebocadas'].index, axis=0, inplace=True)
police_db.drop(police_db[police_db['NOME'] == 'Carreira de Tiro da Escola Superior de Polícia'].index, axis=0, inplace=True)

In [22]:
#resetting index
police_db.reset_index(drop=True, inplace=True)
police_db

,NOME,MORADA,CODPOSTAL,Freguesia
0,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524,1100-524
1,Divisão Policial de Segurança a Transportes Pú...,Estação CP Rossio Ed. Posto do Comando,1200-147,1200-147
2,1ª Esquadra de Segurança a Transportes Públicos,Praça do Marquês de Pombal Estação de Metro (M...,1250-161,1250-161
3,Esquadra de Investigação Criminal,"Estação CP Rossio, Edifício do Chefe da Estação",1200-147,1200-147
4,Tribunal de Monsanto - Esquadra Especial,Estrada do Forte (Monsanto) Tribunal,1500-624,1500-624
5,4º Esquadra de Segurança a Transportes Públicos,"Avenida Dom João II, Estação do Oriente Lt. 01...",1990-233,1990-233
6,Direção Nacional da PSP - Departamento de Arma...,"Travessa da Fábrica dos Pentes 22, 1º",1269-003,1269-003
7,Corpo de Intervenção,"Calçada da Ajuda, 23",1300-006,1300-006
8,Esquadra de Turismo,Praça dos Restauradores - Palácio Foz,1250-187,1250-187
9,Posto de Polícia,"Rua José António Serrano Bloco Central, R/C",1150-199,1150-199
10,Posto de Polícia,Avenida Professor Egas Moniz Hospital de San...,1649-035,1649-035
11,Posto de Polícia,Estrada do Forte do Alto do Duque Hospital S F...,1449-005,1449-005
12,Polícia Municipal,"Rua Cardeal Saraiva, R/C",1070-045,1070-045
13,3ª Esquadra,"Rua da Atalaia 138-144, R/C, Rua de O Século ...",1200-033,1200-033
14,22ª Esquadra LX,"Largo do Rato, 1",1250-185,1250-185
15,2ª Divisão Policial LX,Rua Cidade de Nampula (antiga Rua B2 de Olivai...,1800-105,1800-105
16,Esquadra de Intervenção e Fiscalização Policial,"Avenida Cidade Lourenço Marques, Praceta A",1800-093,1800-093
17,14ª Esquadra LX,Rua Luiz Pacheco Lote 105,1950-244,1950-244
18,16ª Esquadra LX,"Avenida João Paulo II Lote 526, R/C",1950-159,1950-159
19,40ª Esquadra,"Rua Ilha dos Amores, Lote 43901-J, Parque das ...",1990-371,1990-371
20,3ª Divisão Policial LX,"Rua André de Resende, R/C",1500-040,1500-040
21,Esquadra de Segurança,"Palácio de Belém, s/n",1349-022,1349-022
22,Esquadra de Segurança,"Praça de São Bento, s/n",1249-068,1249-068
23,Esquadra de Segurança,"Rua Professor Gomes Teixeira 2, R/C",1350-265,1350-265
24,Esquadra de Segurança,"Rua da Imprensa à Estrela, 4",1200-888,1200-888
25,Esquadra de Segurança,"Avenida João Crisóstomo Casa da Moeda, R/C",1500-624,1500-624
26,Esquadra de Intervenção e Fiscalização Policial,"Rua André de Resende, 1",1500-040,1500-040
27,18ª Esquadra LX,"Rua Afonso Lopes Vieira 2A, R/C",1700-093,1700-093
28,19ª Esquadra LX,"Rua Professor Luís Reis dos Santos, Lote H - 4...",1600-641,1600-641
29,20ª Esquadra LX,Rua André de Resende 1,1500-040,1500-040
30,21ª Esquadra LX,"Rua Marquês de Fronteira Tribunal da Policia, ...",1098-001,1098-001
31,32ª Esquadra,Rua Alfredo Ferraz (antigo Impasse B1 do Bairr...,1600-003,1600-003
32,36ª Esquadra,Rua Prof. Miller Guerra (antigo Impasse A do B...,1600-647,1600-647
33,37ª Esquadra,"Rua Miguel Ângelo de Blasco 25, R/C",1070-181,1070-181
34,41ª Esquadra,"Rua Maria José da Guia, 14 B - Bairro da Cruz ...",1750-358,1750-358
35,42ª Esquadra,"Rua Manuela Porto, 14 - A",1500-422,1500-422
36,43ª Esquadra LX,Rua do Azevinho (Rua B) Quarteirão Central B -...,1500-536,1500-536
37,Posto de Polícia,Rua Albert Einstein (antiga R Norte - C.C.Colo...,1500-676,1500-676
38,4ª Divisão Policial,"Largo do Calvário 6, 1º",1300-113,1300-113
39,24ª Esquadra LX,"Rua Azedo Gneco 84, R/C",1350-039,1350-039
40,26ª Esquadra LX,"Praça Afonso de Albuquerque PSP, R/C",1300-004,1300-004
41,28ª Esquadra LX,"Largo do Calvário 6, R/C",1300-113,1300-113
42,30ª Esquadra,"Rua Miguel Lupi 6, R/C",1200-725,1200-725
43,10ª Esquadra Lx,"Rua de Arroios, 164 - A",1000-061,1000-061
44,12ª Esquadra LX,"Rua Américo Durão, 3, A-B",1900-063,1900-063

In [23]:
#inserting freguesia name
police_db.at[0, 'Freguesia'] = 'São Nicolau'
police_db.at[1, 'Freguesia'] = 'Santo António'
police_db.at[2, 'Freguesia'] = 'Santa Maria Maior'
police_db.at[3, 'Freguesia'] = 'Santo António'
police_db.at[4, 'Freguesia'] = 'Benfica'
police_db.at[5, 'Freguesia'] = 'Olivais'
police_db.at[6, 'Freguesia'] = 'Santo António'
police_db.at[7, 'Freguesia'] = 'Ajuda'
police_db.at[8, 'Freguesia'] = 'Santa Maria Maior'
police_db.at[9, 'Freguesia'] = 'Arroios'
police_db.at[10, 'Freguesia'] = 'Campo Grande'
police_db.at[11, 'Freguesia'] = 'Belém'
police_db.at[12, 'Freguesia'] = 'Campolide'
police_db.at[13, 'Freguesia'] = 'Misericórdia'
police_db.at[14, 'Freguesia'] = 'Santo António'
police_db.at[15, 'Freguesia'] = 'Olivais'
police_db.at[16, 'Freguesia'] = 'Olivais'
police_db.at[17, 'Freguesia'] = 'Marvila'
police_db.at[18, 'Freguesia'] = 'Marvila'
police_db.at[19, 'Freguesia'] = 'Moscavide'
police_db.at[20, 'Freguesia'] = 'Benfica'
police_db.at[21, 'Freguesia'] = 'Benfica'
police_db.at[22, 'Freguesia'] = 'Belém'
police_db.at[23, 'Freguesia'] = 'Belém'
police_db.at[24, 'Freguesia'] = 'Estrela'
police_db.at[25, 'Freguesia'] = 'Benfica'
police_db.at[26, 'Freguesia'] = 'Benfica'

In [24]:
police_db.at[27, 'Freguesia'] = 'Campo Grande'
police_db.at[28, 'Freguesia'] = 'Lumiar'
police_db.at[29, 'Freguesia'] = 'Benfica'
police_db.at[30, 'Freguesia'] = 'Campolide'
police_db.at[31, 'Freguesia'] = 'Carnide'
police_db.at[32, 'Freguesia'] = 'Carnide'
police_db.at[33, 'Freguesia'] = 'Campolide'
police_db.at[34, 'Freguesia'] = 'Lumiar'
police_db.at[35, 'Freguesia'] = 'Carnide'
police_db.at[36, 'Freguesia'] = 'Benfica'
police_db.at[37, 'Freguesia'] = 'Carnide'
police_db.at[38, 'Freguesia'] = 'Alcântara'
police_db.at[39, 'Freguesia'] = 'Campo de Ourique'
police_db.at[40, 'Freguesia'] = 'Belém'
police_db.at[41, 'Freguesia'] = 'Alcântara'
police_db.at[42, 'Freguesia'] = 'Estrela'
police_db.at[43, 'Freguesia'] = 'Santa Maria Maior'
police_db.at[44, 'Freguesia'] = 'Areeiro'

In [25]:
police_db

,NOME,MORADA,CODPOSTAL,Freguesia
0,2ª Esquadra,"Rua da Prata nº 38, 1100-419 Lisboa c/ Rua de ...",1100-524,São Nicolau
1,Divisão Policial de Segurança a Transportes Pú...,Estação CP Rossio Ed. Posto do Comando,1200-147,Santo António
2,1ª Esquadra de Segurança a Transportes Públicos,Praça do Marquês de Pombal Estação de Metro (M...,1250-161,Santa Maria Maior
3,Esquadra de Investigação Criminal,"Estação CP Rossio, Edifício do Chefe da Estação",1200-147,Santo António
4,Tribunal de Monsanto - Esquadra Especial,Estrada do Forte (Monsanto) Tribunal,1500-624,Benfica
5,4º Esquadra de Segurança a Transportes Públicos,"Avenida Dom João II, Estação do Oriente Lt. 01...",1990-233,Olivais
6,Direção Nacional da PSP - Departamento de Arma...,"Travessa da Fábrica dos Pentes 22, 1º",1269-003,Santo António
7,Corpo de Intervenção,"Calçada da Ajuda, 23",1300-006,Ajuda
8,Esquadra de Turismo,Praça dos Restauradores - Palácio Foz,1250-187,Santa Maria Maior
9,Posto de Polícia,"Rua José António Serrano Bloco Central, R/C",1150-199,Arroios
10,Posto de Polícia,Avenida Professor Egas Moniz Hospital de San...,1649-035,Campo Grande
11,Posto de Polícia,Estrada do Forte do Alto do Duque Hospital S F...,1449-005,Belém
12,Polícia Municipal,"Rua Cardeal Saraiva, R/C",1070-045,Campolide
13,3ª Esquadra,"Rua da Atalaia 138-144, R/C, Rua de O Século ...",1200-033,Misericórdia
14,22ª Esquadra LX,"Largo do Rato, 1",1250-185,Santo António
15,2ª Divisão Policial LX,Rua Cidade de Nampula (antiga Rua B2 de Olivai...,1800-105,Olivais
16,Esquadra de Intervenção e Fiscalização Policial,"Avenida Cidade Lourenço Marques, Praceta A",1800-093,Olivais
17,14ª Esquadra LX,Rua Luiz Pacheco Lote 105,1950-244,Marvila
18,16ª Esquadra LX,"Avenida João Paulo II Lote 526, R/C",1950-159,Marvila
19,40ª Esquadra,"Rua Ilha dos Amores, Lote 43901-J, Parque das ...",1990-371,Moscavide
20,3ª Divisão Policial LX,"Rua André de Resende, R/C",1500-040,Benfica
21,Esquadra de Segurança,"Palácio de Belém, s/n",1349-022,Benfica
22,Esquadra de Segurança,"Praça de São Bento, s/n",1249-068,Belém
23,Esquadra de Segurança,"Rua Professor Gomes Teixeira 2, R/C",1350-265,Belém
24,Esquadra de Segurança,"Rua da Imprensa à Estrela, 4",1200-888,Estrela
25,Esquadra de Segurança,"Avenida João Crisóstomo Casa da Moeda, R/C",1500-624,Benfica
26,Esquadra de Intervenção e Fiscalização Policial,"Rua André de Resende, 1",1500-040,Benfica
27,18ª Esquadra LX,"Rua Afonso Lopes Vieira 2A, R/C",1700-093,Campo Grande
28,19ª Esquadra LX,"Rua Professor Luís Reis dos Santos, Lote H - 4...",1600-641,Lumiar
29,20ª Esquadra LX,Rua André de Resende 1,1500-040,Benfica
30,21ª Esquadra LX,"Rua Marquês de Fronteira Tribunal da Policia, ...",1098-001,Campolide
31,32ª Esquadra,Rua Alfredo Ferraz (antigo Impasse B1 do Bairr...,1600-003,Carnide
32,36ª Esquadra,Rua Prof. Miller Guerra (antigo Impasse A do B...,1600-647,Carnide
33,37ª Esquadra,"Rua Miguel Ângelo de Blasco 25, R/C",1070-181,Campolide
34,41ª Esquadra,"Rua Maria José da Guia, 14 B - Bairro da Cruz ...",1750-358,Lumiar
35,42ª Esquadra,"Rua Manuela Porto, 14 - A",1500-422,Carnide
36,43ª Esquadra LX,Rua do Azevinho (Rua B) Quarteirão Central B -...,1500-536,Benfica
37,Posto de Polícia,Rua Albert Einstein (antiga R Norte - C.C.Colo...,1500-676,Carnide
38,4ª Divisão Policial,"Largo do Calvário 6, 1º",1300-113,Alcântara
39,24ª Esquadra LX,"Rua Azedo Gneco 84, R/C",1350-039,Campo de Ourique
40,26ª Esquadra LX,"Praça Afonso de Albuquerque PSP, R/C",1300-004,Belém
41,28ª Esquadra LX,"Largo do Calvário 6, R/C",1300-113,Alcântara
42,30ª Esquadra,"Rua Miguel Lupi 6, R/C",1200-725,Estrela
43,10ª Esquadra Lx,"Rua de Arroios, 164 - A",1000-061,Santa Maria Maior
44,12ª Esquadra LX,"Rua Américo Durão, 3, A-B",1900-063,Areeiro

## Merge Population into Freguesia

In [41]:
freguesias_db.head()

# 1 Create a dictionary for matching old FREGUESIAs with new Fregeusias with New as keys and List of old as value
dict_change=freguesias_db[['CURRENT FREGUESIAS','OLD FREGUESIAS']].to_dict('list')

liste_old_Fregue = [s.split(' + ') for s in freguesias_db['OLD FREGUESIAS']]
liste_new_Fregue = freguesias_db['CURRENT FREGUESIAS']

dictionaryNEW_OLD = dict(zip(liste_new_Fregue,liste_old_Fregue))

#print(len(dictionaryNEW_OLD))


# 2change list of values = OLD FREGUESIAS to key and add New Frequesias as value
dictionaryOLD_NEW={} 
count=-1
for value in dictionaryNEW_OLD.values():
    count +=1
    for x in value:
        dictionaryOLD_NEW[x]=list(dictionaryNEW_OLD.keys())[count]
#print(len(dictionaryOLD_NEW))
        
# 3 import dictionary in to a dataframe
dfOLD_NEW=pd.DataFrame.from_dict(dictionaryOLD_NEW, orient='index', columns=['CURRENT FREGUESIAS']).reset_index()
dfOLD_NEW.columns=['FREGUESIAS','CURRENT FREGUESIAS']
#print(dfOLD_NEW)

# 4 add the New FREGUESIAs to the population dataframe
pop_new = pd.merge(pop_db, dfOLD_NEW, on='FREGUESIAS', how ='left')
#print(pop_new)
#print(pop_db)
# 5 group the population by the new FREGUESIAs
pop_grouped = pop_new.groupby(['CURRENT FREGUESIAS'], as_index=False).agg({'TOTAL RESIDENTS':'sum'})

# 6 merge the population with the frequesias
freg_with_pop= pd.merge(freguesias_db, pop_grouped, on='CURRENT FREGUESIAS')
freg_with_pop

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,TOTAL RESIDENTS
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,11855
1,MARVILA,7122521.90,MARVILA,38102
2,AJUDA,2876647.11,AJUDA,15584
3,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,20131
4,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,12961
5,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,31110
6,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,16561
7,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,20116
8,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,32262
9,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA,9935
10,AVENIDAS NOVAS,2994523.99,NOSSA SENHORA DE FÁTIMA + SÃO SEBASTIÃO DA PED...,21625
11,CARNIDE,3688827.32,CARNIDE,23316
12,SÃO DOMINGOS DE BENFICA,4294403.21,SÃO DOMINGOS DE BENFICA,33745
13,BEATO,2483775.04,BEATO,12429
14,CAMPOLIDE,2774372.95,CAMPOLIDE,15460
15,ALCÂNTARA,5074843.76,ALCÂNTARA,13943
16,CAMPO DE OURIQUE,1651405.17,SANTA ISABEL + SANTO CONDESTÁVEL,22132
17,SÃO VICENTE,1985855.99,GRAÇA + SANTA ENGRÁCIA + SÃO VICENTE DE FORA,14575
18,OLIVAIS,8088293.95,SANTA MARIA DOS OLIVAIS,51036
19,MISERICÓRDIA,2192198.78,ENCARNAÇÃO + MERCÊS + SANTA CATARINA + SÃO PAULO,13041
20,LUMIAR,6574930.77,LUMIAR,41163
21,PENHA DE FRANÇA,2710760.87,PENHA DE FRANÇA + SÃO JOÃO,27967
22,BENFICA,8024544.82,BENFICA,36821

## Cleaning Average Cost of Living

In [52]:
cost_of_living_db = pd.read_excel('Avg cost of living.xlsx')

cost_of_living_db['Current Freguesias'] = cost_of_living_db['Current Freguesias'].str.upper()
cost_of_living_db.columns = ['CURRENT FREGUESIAS', 'AVERAGE RENT IN EUROS']

cost_of_living_db.head()

  CURRENT FREGUESIAS  AVERAGE RENT IN EUROS
0              AJUDA                 271.61
1          ALCÂNTARA                 308.09
2           ALVALADE                 381.83
3            AREEIRO                 410.26
4            ARROIOS                 372.80

In [74]:
freq_with_pop_COSTofLi = pd.merge(freg_with_pop, cost_of_living_db, on='CURRENT FREGUESIAS', how='left')
freq_with_pop_COSTofLi
#print(len(freg_with_pop))
#print(len(freq_with_pop_COSTofLi))

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,TOTAL RESIDENTS,AVERAGE RENT IN EUROS
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,11855,386.26
1,MARVILA,7122521.90,MARVILA,38102,212.79
2,AJUDA,2876647.11,AJUDA,15584,271.61
3,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,20131,410.26
4,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,12961,273.20
5,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,31110,381.83
6,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,16561,431.90
7,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,20116,376.04
8,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,32262,372.80
9,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA,9935,280.87
10,AVENIDAS NOVAS,2994523.99,NOSSA SENHORA DE FÁTIMA + SÃO SEBASTIÃO DA PED...,21625,421.45
11,CARNIDE,3688827.32,CARNIDE,23316,317.42
12,SÃO DOMINGOS DE BENFICA,4294403.21,SÃO DOMINGOS DE BENFICA,33745,412.61
13,BEATO,2483775.04,BEATO,12429,255.74
14,CAMPOLIDE,2774372.95,CAMPOLIDE,15460,325.87
15,ALCÂNTARA,5074843.76,ALCÂNTARA,13943,308.09
16,CAMPO DE OURIQUE,1651405.17,SANTA ISABEL + SANTO CONDESTÁVEL,22132,344.07
17,SÃO VICENTE,1985855.99,GRAÇA + SANTA ENGRÁCIA + SÃO VICENTE DE FORA,14575,285.35
18,OLIVAIS,8088293.95,SANTA MARIA DOS OLIVAIS,51036,330.69
19,MISERICÓRDIA,2192198.78,ENCARNAÇÃO + MERCÊS + SANTA CATARINA + SÃO PAULO,13041,321.15
20,LUMIAR,6574930.77,LUMIAR,41163,428.16
21,PENHA DE FRANÇA,2710760.87,PENHA DE FRANÇA + SÃO JOÃO,27967,330.75
22,BENFICA,8024544.82,BENFICA,36821,324.95

In [75]:
# rename main file
main_db= freq_with_pop_COSTofLi

## Creating Density column

In [76]:
main_db['DENSITY'] = main_db['AREA'] / main_db['TOTAL RESIDENTS']
main_db.head(10)

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,TOTAL RESIDENTS,AVERAGE RENT IN EUROS,DENSITY
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,11855,386.26,126.052179
1,MARVILA,7122521.90,MARVILA,38102,212.79,186.933019
2,AJUDA,2876647.11,AJUDA,15584,271.61,184.589779
3,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,20131,410.26,85.390814
4,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,12961,273.20,232.357960
5,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,31110,381.83,171.705272
6,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,16561,431.90,629.608652
7,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,20116,376.04,228.877310
8,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,32262,372.80,65.955982
9,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA,9935,280.87,337.751644

## Summary Statistics

In [77]:
main_db.describe()

               AREA  TOTAL RESIDENTS  AVERAGE RENT IN EUROS     DENSITY
count  2.300000e+01        23.000000              23.000000   23.000000
mean   4.113873e+06     23298.695652             339.298261  192.542209
std    2.437941e+06     11194.274906              60.571762  119.686334
min    1.494349e+06      9935.000000             212.790000   65.955982
25%    2.337987e+06     14259.000000             296.720000  131.755635
50%    3.011592e+06     20131.000000             330.690000  168.100512
75%    5.208297e+06     31686.000000             384.045000  208.885498
max    1.042695e+07     51036.000000             431.900000  629.608652

## Relative values

In [78]:
# 1 per person


# 2 per Density

## Idea for Binning

In [79]:
#### apply for relative Values!!
mpg_labels= [x for x in range(1,12)]
main_db['BINNED POPULATION'] = pd.qcut(main_db['TOTAL RESIDENTS'], 11, labels = mpg_labels)

main_db

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,TOTAL RESIDENTS,AVERAGE RENT IN EUROS,DENSITY,BINNED POPULATION
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,11855,386.26,126.052179,1
1,MARVILA,7122521.90,MARVILA,38102,212.79,186.933019,10
2,AJUDA,2876647.11,AJUDA,15584,271.61,184.589779,4
3,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,20131,410.26,85.390814,6
4,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,12961,273.20,232.357960,2
5,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,31110,381.83,171.705272,8
6,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,16561,431.90,629.608652,5
7,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,20116,376.04,228.877310,5
8,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,32262,372.80,65.955982,9
9,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA,9935,280.87,337.751644,1
10,AVENIDAS NOVAS,2994523.99,NOSSA SENHORA DE FÁTIMA + SÃO SEBASTIÃO DA PED...,21625,421.45,138.475098,6
11,CARNIDE,3688827.32,CARNIDE,23316,317.42,158.210127,7
12,SÃO DOMINGOS DE BENFICA,4294403.21,SÃO DOMINGOS DE BENFICA,33745,412.61,127.260430,9
13,BEATO,2483775.04,BEATO,12429,255.74,199.837078,1
14,CAMPOLIDE,2774372.95,CAMPOLIDE,15460,325.87,179.454913,4
15,ALCÂNTARA,5074843.76,ALCÂNTARA,13943,308.09,363.970721,3
16,CAMPO DE OURIQUE,1651405.17,SANTA ISABEL + SANTO CONDESTÁVEL,22132,344.07,74.616174,7
17,SÃO VICENTE,1985855.99,GRAÇA + SANTA ENGRÁCIA + SÃO VICENTE DE FORA,14575,285.35,136.250840,3
18,OLIVAIS,8088293.95,SANTA MARIA DOS OLIVAIS,51036,330.69,158.482129,11
19,MISERICÓRDIA,2192198.78,ENCARNAÇÃO + MERCÊS + SANTA CATARINA + SÃO PAULO,13041,321.15,168.100512,2
20,LUMIAR,6574930.77,LUMIAR,41163,428.16,159.729144,11
21,PENHA DE FRANÇA,2710760.87,PENHA DE FRANÇA + SÃO JOÃO,27967,330.75,96.927124,8
22,BENFICA,8024544.82,BENFICA,36821,324.95,217.933919,10

## Rank of Cost of Living

In [81]:
mpg_labels= [x for x in range(1,23)]
main_db['RANK COST OF LIVING'] = pd.qcut(main_db['AVERAGE RENT IN EUROS'], 22, labels = mpg_labels)

main_db

,CURRENT FREGUESIAS,AREA,OLD FREGUESIAS,TOTAL RESIDENTS,AVERAGE RENT IN EUROS,DENSITY,BINNED POPULATION,RANK COST OF LIVING
0,SANTO ANTÓNIO,1494348.58,CORAÇÃO DE JESUS + SÃO JOSÉ + SÃO MAMEDE,11855,386.26,126.052179,1,17
1,MARVILA,7122521.90,MARVILA,38102,212.79,186.933019,10,1
2,AJUDA,2876647.11,AJUDA,15584,271.61,184.589779,4,2
3,AREEIRO,1719002.47,ALTO DO PINA + SÃO JOÃO DE DEUS,20131,410.26,85.390814,6,18
4,SANTA MARIA MAIOR,3011591.52,CASTELO + MADALENA + MÁRTIRES + SACRAMENTO + S...,12961,273.20,232.357960,2,3
5,ALVALADE,5341751.02,ALVALADE + CAMPO GRANDE + SÃO JOÃO DE BRITO,31110,381.83,171.705272,8,16
6,BELÉM,10426948.88,SANTA MARIA DE BELÉM + SÃO FRANCISCO XAVIER,16561,431.90,629.608652,5,22
7,ESTRELA,4604095.97,LAPA + PRAZERES + SANTOS-O-VELHO,20116,376.04,228.877310,5,15
8,ARROIOS,2127871.88,ANJOS + PENA + SÃO JORGE DE ARROIOS,32262,372.80,65.955982,9,14
9,SANTA CLARA,3355562.58,AMEIXOEIRA + CHARNECA,9935,280.87,337.751644,1,4
10,AVENIDAS NOVAS,2994523.99,NOSSA SENHORA DE FÁTIMA + SÃO SEBASTIÃO DA PED...,21625,421.45,138.475098,6,20
11,CARNIDE,3688827.32,CARNIDE,23316,317.42,158.210127,7,7
12,SÃO DOMINGOS DE BENFICA,4294403.21,SÃO DOMINGOS DE BENFICA,33745,412.61,127.260430,9,19
13,BEATO,2483775.04,BEATO,12429,255.74,199.837078,1,1
14,CAMPOLIDE,2774372.95,CAMPOLIDE,15460,325.87,179.454913,4,10
15,ALCÂNTARA,5074843.76,ALCÂNTARA,13943,308.09,363.970721,3,6
16,CAMPO DE OURIQUE,1651405.17,SANTA ISABEL + SANTO CONDESTÁVEL,22132,344.07,74.616174,7,13
17,SÃO VICENTE,1985855.99,GRAÇA + SANTA ENGRÁCIA + SÃO VICENTE DE FORA,14575,285.35,136.250840,3,5
18,OLIVAIS,8088293.95,SANTA MARIA DOS OLIVAIS,51036,330.69,158.482129,11,11
19,MISERICÓRDIA,2192198.78,ENCARNAÇÃO + MERCÊS + SANTA CATARINA + SÃO PAULO,13041,321.15,168.100512,2,8
20,LUMIAR,6574930.77,LUMIAR,41163,428.16,159.729144,11,21
21,PENHA DE FRANÇA,2710760.87,PENHA DE FRANÇA + SÃO JOÃO,27967,330.75,96.927124,8,12
22,BENFICA,8024544.82,BENFICA,36821,324.95,217.933919,10,9

## Compare Social Infrastructure and Cost of Living